### ISSUE TITLE
Emacs 25.3 crashes

### ISSUE THREAD

**Issue by amake** [flycheck/docker-tools#6]
I'm using your Docker images to test one of my projects in CI, and I find that the current `flycheck/emacs-cask:25.3` image's emacs crashes when executed. You can reproduce like so:

```sh
% docker run --rm -it flycheck/emacs-cask:25.3 emacs
Fatal error 4: Illegal instruction
Backtrace:
emacs[0x4a7bf9]
emacs[0x48f5bc]
emacs[0x4a68ee]
emacs[0x4a6b13]
emacs[0x4a6bb9]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7f660cf5a890]
emacs[0x4eb990]
emacs[0x405ec8]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f660c7dab97]
emacs[0x406d89]
```

The image's ID is `9a7c34abb84e`.

Edit: Actually `emacs --version` works, but just `emacs` doesn't work, and neither does the execution used in my test, which is `emacs -Q -L .  --eval '(setq byte-compile-error-on-warn t)' -batch -f batch-byte-compile <project el files>`.

Also I should note that the 26.2 image (ID `2ff0c2eb4547`) works, but the 24.5 image (ID `0d36fd8cbfd5`) does not.

**Comment by fmdkdd** [comment]
Yes indeed, I can reproduce on my machine.  These images work on Travis though, and that is also where they are built.  So it may be caused by something in the environment that differs?

I don't have time to investigate, but I welcome solutions.

**Comment by carrete** [comment]
To compile emacs, I had to run:

    docker run --privileged --pid=host alpine sh -c "echo 0 > /proc/sys/kernel/randomize_va_space"

This has some security-related implications, FYI. From https://github.com/moby/moby/issues/22801#issuecomment-220658073

**Comment by fmdkdd** [comment]
@carrete yes, but as Travis uses an outdated docker version, we can build them fine without disabling ASLR.  Also, Emacs 27.1 and up have a portable dumper.

Anyway, I cannot reproduce the segfault with the latest images.  Feel free to reopen if the issue strikes again.
